apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-demo
spec:
  revisionHistoryLimit: 2
  template:
    spec:
      containers:
      - name: web-demo
        image: mjcheveste/web-example
        tag: 1.0.3
