apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-chart.fullname" . }}
  labels:
    app: {{ include "my-chart.name" . }}
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: {{ include "my-chart.name" . }}