replicaCount: 1
image:
  repository: mjcheveste/web-example
  tag: 1.0.1
  pullPolicy: always
ingress:
  enabled: true
  hostname: your-hostname
  annotations:
    kubernetes.io/ingress.class: nginx
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
service:
  port: 80