---
namespace: develop
replicas:
  - name: web-demo
    count: 2
images:
  - name: mjcheveste/web-example
    newTag: 1.0.3
resources:
  - ../../../base



#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization
#namespace: develop
#bases:
#- ../../../base